name: Slipper Developer Issue
description: Reserved for Slipper Developers. Join our support server for support.

body:
    - type: markdown
      attributes:
          value: |
              # This form is reserved for Slipper Developers. Do not open an issue.

              Instead, use [our GitHub](https://github.com/slipcords/Slipper/issues) for help and reporting issues.

              Your issue will be closed immediately with no comment and you will be blocked if you ignore this.

              This is because 99% of issues are not actually bugs, but rather user or system issues and it adds a lot of noise to our development process.
    - type: textarea
      id: content
      attributes:
          label: Content
      validations:
          required: true
